name: quick_chat_wms_example
description: "Demonstrates how to use the quick_chat_wms plugin."

publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  quick_chat_wms:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
